feat(obs): OTEL logs to ES; add ELK; refactor logger
- Add otel/log + otlploggrpc; expose 4317.
- Add Elasticsearch + Kibana with auto data view.
- Collector logs pipeline -> ES (ECS mapping).
- Logger: stdout+OTLP tee, LoggerConfig init, rename addField→addFieldFromContext.

BREAKING CHANGE: Init now takes LoggerConfig; addField renamed.

diff --git a/infra/otel/docker-compose.yaml b/infra/otel/docker-compose.yaml
--- a/infra/otel/docker-compose.yaml
+++ b/infra/otel/docker-compose.yaml
@@ -10,6 +10,7 @@ services:
       - "${OTEL_HTTP_PORT}:4318" # OTLP HTTP port
       - "8888:8888" # Collector metrics endpoint
       - "8889:8889" # zpages debug endpoint
+      - "4317:4317" # OTLP endpoint for receiving logs 
     restart: unless-stopped
     # Auto-restart on failure, not on manual stop
     networks:
@@ -26,6 +27,9 @@ services:
     depends_on:
       jaeger:
         condition: service_healthy
+      elasticsearch:
+        condition: service_healthy
+
 
   jaeger:
     image: jaegertracing/jaeger:2.6.0
@@ -57,6 +61,108 @@ services:
     networks:
       - messenger-network
 
+  elasticsearch:
+    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.4
+    container_name: elasticsearch
+    environment:
+      - discovery.type=single-node
+      - xpack.security.enabled=false
+      - cluster.name=es-docker-cluster
+    
+    volumes:
+      - es_data:/usr/share/elasticsearch/data
+    
+    ports:
+      - "9200:9200"
+    
+    healthcheck:
+      test: ["CMD-SHELL", "curl -fsS http://localhost:9200/_cluster/health >/dev/null"]
+      interval: 10s
+      timeout: 5s 
+      retries: 20
+      start_period: 30s
+    
+    restart: unless-stopped
+
+    networks:
+      - messenger-network
+
+  kibana:
+    image: docker.elastic.co/kibana/kibana:9.0.4
+    container_name: kibana
+    environment:
+      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
+      - XPACK_SECURITY_ENABLED=false
+    
+    depends_on:
+      elasticsearch:
+        condition: service_healthy
+    
+    ports:
+      - "5601:5601"
+    
+    healthcheck:
+      test: ["CMD-SHELL", "curl -fsS http://localhost:5601/api/status >/dev/null"]
+      interval: 10s
+      timeout: 5s
+      retries: 20
+      start_period: 30s
+    
+    restart: unless-stopped
+    networks:
+      - messenger-network
+
+  kibana-init: # This is special container for auto creating data view in Kibana
+    image: alpine:3.21
+    container_name: kibana-init
+    depends_on:
+      kibana:
+        condition: service_healthy
+    
+    command: 
+      - sh
+      - -c
+      - |
+        set -e # stop scipt after first error
+        
+        echo "Installing curl and jq..."
+        apk add --no-cache curl jq >/dev/null 2>&1
+        
+        echo "Waiting for Kibana..."
+        # max 60 attempts with delay 2 seconds
+        for i in $$(seq 1 60); do
+          if curl -sSf http://kibana:5601/api/status >/dev/null; then break; fi
+          sleep 2
+        done
+        
+        echo "Creating Data View easy-logs* ..."
+        RESPONSE=$$(curl -sS -X POST http://kibana:5601/api/data_views/data_view \
+          -H "kbn-xsrf: true" \
+          -H "Content-Type: application/json" \
+          --data '{"data_view":{"title":"logs*","name":"Logs","timeFieldName":"@timestamp","allowNoIndex":true},"override":true}' || echo "{}")
+        
+        echo "Response: $$RESPONSE"
+        DATA_VIEW_ID=$$(echo "$$RESPONSE" | jq -r ".data_view.id // empty")
+        echo "Data View ID: $$DATA_VIEW_ID"
+        
+        # Making Data View default in Kibana
+        if [ -n "$$DATA_VIEW_ID" ]; then
+          echo "Setting as default data view..."
+          curl -sS -X POST http://kibana:5601/api/data_views/default \
+            -H "kbn-xsrf: true" \
+            -H "Content-Type: application/json" \
+            -d "{\"data_view_id\": \"$$DATA_VIEW_ID\", \"force\": true}" || true
+          echo "Default data view set successfully."
+        else
+          echo "Failed to get data view ID"
+        fi
+        echo "Done."
+    
+    networks:
+      - messenger-network
+    
+    restart: "no"
+
 networks:
   messenger-network:
     external: true
@@ -64,3 +170,6 @@ networks:
 volumes: 
   jaeger_data: 
   jaeger_key: # Named volume for Jaeger indexes
+
+  es_data: # Elacstic search volume for storing logs
+
